import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# ASR Phase 3.5: GPU Throughput Preflight Benchmark (Google Colab / Cloud GPU)\n",
                "\n",
                "**Project:** Vietnamese Speech-to-Text Research (Phase 3.5 Full E1 Preflight)  \n",
                "**Model:** `vinai/PhoWhisper-tiny` (Pinned revision: `cc51d32be916efebde04ff549854fa1741cb5c02`)  \n",
                "**Target Architecture:** PEFT LoRA ($r=8, \\alpha=16$, dropout=0.05, `target_modules=['q_proj', 'v_proj']`, `bias='none'`)  \n",
                "**Optimization Budget:** Micro Batch = 4, Grad Accum = 8, Effective Batch = 32, FP16 mixed precision  \n",
                "**Full Training Budget:** 834 steps/epoch × 3 epochs = **2,502 optimizer steps** (80,064 sample exposures)  \n",
                "\n",
                "> **MANDATORY PREFLIGHT BENCHMARK:**  \n",
                "> 1. Execute 5 warmup optimizer steps (excluded from timing).  \n",
                "> 2. Reset peak memory stats via `torch.cuda.reset_peak_memory_stats()`.  \n",
                "> 3. Measure 50 optimizer steps with `torch.cuda.synchronize()`.  \n",
                "> 4. Record `torch.cuda.max_memory_allocated()` and `torch.cuda.max_memory_reserved()`.  \n",
                "> 5. Derive `ESTIMATED FULL E1 DURATION` based on measured step latency."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 0. Install Dependencies\n",
                "Installs audited dependencies pinned to `peft==0.21.0` and `accelerate==1.15.0` matching repository state."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!pip install -q peft==0.21.0 accelerate==1.15.0 transformers==4.49.0 soundfile jiwer pandas pyyaml"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Hardware Verification & CUDA Diagnostic\n",
                "Inspect GPU model, CUDA driver, PyTorch CUDA build, and available VRAM."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import sys\n",
                "import peft\n",
                "import transformers\n",
                "import accelerate\n",
                "\n",
                "print(f\"OS / Platform:      {sys.platform}\")\n",
                "print(f\"Python Version:     {sys.version.split()[0]}\")\n",
                "print(f\"PyTorch Version:    {torch.__version__}\")\n",
                "print(f\"PEFT Version:       {peft.__version__}\")\n",
                "print(f\"Transformers Ver:   {transformers.__version__}\")\n",
                "print(f\"Accelerate Ver:     {accelerate.__version__}\")\n",
                "print(f\"CUDA Available:     {torch.cuda.is_available()}\")\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    device_name = torch.cuda.get_device_name(0)\n",
                "    total_vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n",
                "    total_vram_mb = torch.cuda.get_device_properties(0).total_memory / (1024**2)\n",
                "    cuda_ver = torch.version.cuda\n",
                "    print(f\"GPU Model:          {device_name}\")\n",
                "    print(f\"Total VRAM:         {total_vram_mb:.1f} MB ({total_vram_gb:.2f} GB)\")\n",
                "    print(f\"CUDA Version:       {cuda_ver}\")\n",
                "else:\n",
                "    print(\"WARNING: No CUDA GPU detected! Please change runtime type to GPU (T4 / A100 / L4).\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Load Base Model with Pinned Revision & Setup LoRA\n",
                "Loads `vinai/PhoWhisper-tiny` pinned to commit `cc51d32be916efebde04ff549854fa1741cb5c02` and attaches PEFT LoRA."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from peft import LoraConfig, get_peft_model\n",
                "from transformers import WhisperForConditionalGeneration, WhisperProcessor\n",
                "\n",
                "MODEL_NAME = \"vinai/PhoWhisper-tiny\"\n",
                "MODEL_REVISION = \"cc51d32be916efebde04ff549854fa1741cb5c02\"\n",
                "\n",
                "processor = WhisperProcessor.from_pretrained(MODEL_NAME, revision=MODEL_REVISION)\n",
                "base_model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME, revision=MODEL_REVISION)\n",
                "\n",
                "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
                "\n",
                "# Frozen LoRA Hyperparameters\n",
                "lora_config = LoraConfig(\n",
                "    r=8,\n",
                "    lora_alpha=16,\n",
                "    lora_dropout=0.05,\n",
                "    target_modules=[\"q_proj\", \"v_proj\"],\n",
                "    bias=\"none\",\n",
                ")\n",
                "model = get_peft_model(base_model, lora_config)\n",
                "model.to(device)\n",
                "\n",
                "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
                "all_params = sum(p.numel() for p in model.parameters())\n",
                "print(f\"Base Model Revision:  {MODEL_REVISION}\")\n",
                "print(f\"Total Parameters:     {all_params:,}\")\n",
                "print(f\"Trainable Parameters: {trainable_params:,} ({100 * trainable_params / all_params:.4f}%)\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Run CUDA Throughput Benchmark (5 Warmup Steps + 50 Measured Steps)\n",
                "Executes exact Full E1 optimization step: Micro Batch = 4, Grad Accum = 8, Effective Batch = 32, FP16 mixed precision."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import time\n",
                "import numpy as np\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "from transformers import get_cosine_schedule_with_warmup\n",
                "import json\n",
                "\n",
                "MICRO_BATCH = 4\n",
                "GRAD_ACCUM = 8\n",
                "EFFECTIVE_BATCH = MICRO_BATCH * GRAD_ACCUM  # 32\n",
                "WARMUP_OPT_STEPS = 5\n",
                "MEASURED_OPT_STEPS = 50\n",
                "TOTAL_BENCH_STEPS = WARMUP_OPT_STEPS + MEASURED_OPT_STEPS\n",
                "LEARNING_RATE = 1e-4\n",
                "WEIGHT_DECAY = 0.01\n",
                "\n",
                "class SyntheticAudioDataset(Dataset):\n",
                "    def __init__(self, size=2500, sample_rate=16000, duration=4.0):\n",
                "        self.size = size\n",
                "        self.audio_len = int(sample_rate * duration)\n",
                "    def __len__(self):\n",
                "        return self.size\n",
                "    def __getitem__(self, idx):\n",
                "        waveform = np.sin(2 * np.pi * 440 * np.linspace(0, 4.0, self.audio_len)).astype(np.float32)\n",
                "        text = \"thực nghiệm kiểm tra hiệu năng hệ thống nhận dạng tiếng việt trên hạ tầng tính toán\"\n",
                "        inputs = processor.feature_extractor(waveform, sampling_rate=16000, return_tensors=\"pt\")\n",
                "        labels = processor.tokenizer(text, return_tensors=\"pt\").input_ids[0]\n",
                "        return {\"input_features\": inputs.input_features[0], \"labels\": labels}\n",
                "\n",
                "def collate_fn(batch):\n",
                "    input_features = torch.stack([item[\"input_features\"] for item in batch])\n",
                "    labels = [item[\"labels\"] for item in batch]\n",
                "    max_len = max(len(l) for l in labels)\n",
                "    padded_labels = torch.full((len(labels), max_len), -100, dtype=torch.long)\n",
                "    for i, l in enumerate(labels):\n",
                "        padded_labels[i, :len(l)] = l\n",
                "    return {\"input_features\": input_features, \"labels\": padded_labels}\n",
                "\n",
                "dataset = SyntheticAudioDataset(size=TOTAL_BENCH_STEPS * EFFECTIVE_BATCH + 128)\n",
                "dataloader = DataLoader(dataset, batch_size=MICRO_BATCH, shuffle=False, collate_fn=collate_fn)\n",
                "\n",
                "optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)\n",
                "total_micro_steps = TOTAL_BENCH_STEPS * GRAD_ACCUM\n",
                "scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=int(total_micro_steps * 0.1), num_training_steps=total_micro_steps)\n",
                "scaler = torch.amp.GradScaler('cuda', enabled=torch.cuda.is_available())\n",
                "\n",
                "model.train()\n",
                "micro_step_count = 0\n",
                "opt_step_count = 0\n",
                "\n",
                "# --- PHASE 1: WARMUP STEPS (EXCLUDED FROM TIMING) ---\n",
                "print(f\"[1/2] Running {WARMUP_OPT_STEPS} warmup optimizer steps (excluded from timing)...\")\n",
                "data_iter = iter(dataloader)\n",
                "while opt_step_count < WARMUP_OPT_STEPS:\n",
                "    batch = next(data_iter)\n",
                "    feat = batch[\"input_features\"].to(device)\n",
                "    lab = batch[\"labels\"].to(device)\n",
                "    with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):\n",
                "        out = model(input_features=feat, labels=lab)\n",
                "        loss = out.loss / GRAD_ACCUM\n",
                "    scaler.scale(loss).backward()\n",
                "    micro_step_count += 1\n",
                "    if micro_step_count % GRAD_ACCUM == 0:\n",
                "        scaler.unscale_(optimizer)\n",
                "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
                "        scaler.step(optimizer)\n",
                "        scaler.update()\n",
                "        optimizer.zero_grad()\n",
                "        scheduler.step()\n",
                "        opt_step_count += 1\n",
                "\n",
                "# --- PHASE 2: SYNCHRONIZATION & PEAK MEMORY RESET ---\n",
                "if torch.cuda.is_available():\n",
                "    torch.cuda.synchronize()\n",
                "    torch.cuda.reset_peak_memory_stats()\n",
                "    torch.cuda.empty_cache()\n",
                "\n",
                "# --- PHASE 3: MEASURED BENCHMARK (50 OPTIMIZER STEPS) ---\n",
                "print(f\"[2/2] Measuring {MEASURED_OPT_STEPS} optimizer steps with CUDA synchronization...\")\n",
                "measured_step_times = []\n",
                "measured_losses = []\n",
                "current_loss = 0.0\n",
                "measured_opt_count = 0\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    torch.cuda.synchronize()\n",
                "start_measured_total = time.time()\n",
                "step_start = time.time()\n",
                "\n",
                "while measured_opt_count < MEASURED_OPT_STEPS:\n",
                "    batch = next(data_iter)\n",
                "    feat = batch[\"input_features\"].to(device)\n",
                "    lab = batch[\"labels\"].to(device)\n",
                "    with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):\n",
                "        out = model(input_features=feat, labels=lab)\n",
                "        loss = out.loss / GRAD_ACCUM\n",
                "    scaler.scale(loss).backward()\n",
                "    current_loss += loss.item() * GRAD_ACCUM\n",
                "    micro_step_count += 1\n",
                "    if micro_step_count % GRAD_ACCUM == 0:\n",
                "        scaler.unscale_(optimizer)\n",
                "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
                "        scaler.step(optimizer)\n",
                "        scaler.update()\n",
                "        optimizer.zero_grad()\n",
                "        scheduler.step()\n",
                "        if torch.cuda.is_available():\n",
                "            torch.cuda.synchronize()\n",
                "        step_dur = time.time() - step_start\n",
                "        measured_step_times.append(step_dur)\n",
                "        measured_losses.append(current_loss)\n",
                "        measured_opt_count += 1\n",
                "        if measured_opt_count % 10 == 0 or measured_opt_count == 1:\n",
                "            print(f\"Measured Step [{measured_opt_count:2d}/{MEASURED_OPT_STEPS}] | Loss: {current_loss:.4f} | Latency: {step_dur:.3f}s\")\n",
                "        current_loss = 0.0\n",
                "        step_start = time.time()\n",
                "\n",
                "if torch.cuda.is_available():\n",
                "    torch.cuda.synchronize()\n",
                "total_measured_time = time.time() - start_measured_total\n",
                "total_measured_samples = measured_opt_count * EFFECTIVE_BATCH\n",
                "measured_samples_per_sec = total_measured_samples / total_measured_time\n",
                "mean_step_time = np.mean(measured_step_times)\n",
                "min_step_time = np.min(measured_step_times)\n",
                "max_step_time = np.max(measured_step_times)\n",
                "step_range = max_step_time - min_step_time\n",
                "\n",
                "# --- MEMORY MEASUREMENTS ---\n",
                "if torch.cuda.is_available():\n",
                "    peak_alloc_mb = torch.cuda.max_memory_allocated() / (1024 * 1024)\n",
                "    peak_res_mb = torch.cuda.max_memory_reserved() / (1024 * 1024)\n",
                "    total_vram_mb = torch.cuda.get_device_properties(0).total_memory / (1024 * 1024)\n",
                "    headroom_mb = total_vram_mb - peak_res_mb\n",
                "else:\n",
                "    peak_alloc_mb = 0.0\n",
                "    peak_res_mb = 0.0\n",
                "    total_vram_mb = 0.0\n",
                "    headroom_mb = 0.0\n",
                "\n",
                "# --- ESTIMATED FULL E1 DURATION ---\n",
                "FULL_E1_OPTIMIZER_STEPS = 2502\n",
                "estimated_e1_duration_sec = FULL_E1_OPTIMIZER_STEPS * mean_step_time\n",
                "estimated_e1_duration_hours = estimated_e1_duration_sec / 3600.0\n",
                "\n",
                "print(\"\\n\" + \"=\" * 70)\n",
                "print(\"CUDA MEASURED BENCHMARK RESULTS (AUDITED & ACCURATE)\")\n",
                "print(\"=\" * 70)\n",
                "print(f\"Device:                     {device}\")\n",
                "print(f\"GPU Model:                  {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}\")\n",
                "print(f\"Measured Optimizer Steps:   {measured_opt_count} steps (Warmup steps excluded: {WARMUP_OPT_STEPS})\")\n",
                "print(f\"Measured Samples Processed: {total_measured_samples} samples\")\n",
                "print(f\"Mean Step Latency:          {mean_step_time:.3f} s / optimizer step\")\n",
                "print(f\"Step Latency Range:         [{min_step_time:.3f}s - {max_step_time:.3f}s] (variation: {step_range:.3f}s)\")\n",
                "print(f\"Measured Throughput:        {measured_samples_per_sec:.2f} samples / second\")\n",
                "print(f\"Peak VRAM Allocated:        {peak_alloc_mb:.2f} MB\")\n",
                "print(f\"Peak VRAM Reserved:         {peak_res_mb:.2f} MB\")\n",
                "print(f\"Remaining VRAM Headroom:    {headroom_mb:.2f} MB\")\n",
                "print(f\"Total Full E1 Steps:        {FULL_E1_OPTIMIZER_STEPS} optimizer steps\")\n",
                "print(f\"ESTIMATED FULL E1 DURATION: {estimated_e1_duration_hours:.2f} hours ({estimated_e1_duration_sec:.1f} s)\")\n",
                "print(\"=\" * 70)\n",
                "\n",
                "res = {\n",
                "    'os': sys.platform,\n",
                "    'python_version': sys.version.split()[0],\n",
                "    'gpu_model': torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU',\n",
                "    'cuda_available': torch.cuda.is_available(),\n",
                "    'cuda_version': torch.version.cuda if torch.cuda.is_available() else 'N/A',\n",
                "    'pytorch_version': torch.__version__,\n",
                "    'peft_version': peft.__version__,\n",
                "    'transformers_version': transformers.__version__,\n",
                "    'accelerate_version': accelerate.__version__,\n",
                "    'base_model': MODEL_NAME,\n",
                "    'model_revision': MODEL_REVISION,\n",
                "    'measured_optimizer_steps': measured_opt_count,\n",
                "    'warmup_steps_excluded': WARMUP_OPT_STEPS,\n",
                "    'mean_seconds_per_optimizer_step': round(mean_step_time, 3),\n",
                "    'min_seconds_per_optimizer_step': round(min_step_time, 3),\n",
                "    'max_seconds_per_optimizer_step': round(max_step_time, 3),\n",
                "    'step_variation_range_sec': round(step_range, 3),\n",
                "    'measured_samples_per_sec': round(measured_samples_per_sec, 2),\n",
                "    'peak_vram_allocated_mb': round(peak_alloc_mb, 2),\n",
                "    'peak_vram_reserved_mb': round(peak_res_mb, 2),\n",
                "    'remaining_vram_headroom_mb': round(headroom_mb, 2),\n",
                "    'total_vram_mb': round(total_vram_mb, 2),\n",
                "    'total_e1_optimizer_steps': FULL_E1_OPTIMIZER_STEPS,\n",
                "    'estimated_full_e1_duration_hours': round(estimated_e1_duration_hours, 2),\n",
                "    'estimated_full_e1_duration_sec': round(estimated_e1_duration_sec, 1)\n",
                "}\n",
                "\n",
                "with open('full_e1_cuda_measurement.json', 'w') as f:\n",
                "    json.dump(res, f, indent=2)\n",
                "print(\"Results saved to full_e1_cuda_measurement.json\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbformat": 4,
            "nbformat_minor": 2,
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

output_path_root = r"D:\Vietnamese_ASR_Week6\ASR_PHASE3_5_GPU_THROUGHPUT_PREFLIGHT.ipynb"
with open(output_path_root, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print(f"Updated {output_path_root}")

output_path_app = r"D:\Vietnamese_ASR_Week6\vietnamese_asr_app\ASR_PHASE3_5_GPU_THROUGHPUT_PREFLIGHT.ipynb"
with open(output_path_app, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print(f"Updated {output_path_app}")
